[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [
    { access = "read", path = "./tree.json" }
] 

rpc_endpoints = { sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}" }

remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
